FROM alpine:3.19.1

RUN apk add --no-cache bash curl sed sshfs rsync openssh openssh-sftp-server python3 rdiff-backup encfs gocryptfs
RUN apk add wol --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/

