FROM alpine:3.20.0

RUN apk add --no-cache bash util-linux curl sed sshfs rsync openssh openssh-sftp-server python3 rdiff-backup encfs gocryptfs
RUN apk add wol --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/

