name: Docker

on:
  push:
    branches:
      - master
    
jobs:
  push:
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build/Push image
        run: |
          [ "${GITHUB_REF##*/}" == "master" ] && export PUSH=true
          hack/build-push-from-git-changes.sh
