name: Docker

on:
  push:
    
jobs:
  push:
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build/Push image
        run: |
          branch=${GITHUB_REF##*/}
          if [ "$branch" == "master" ]; then
            export PUSH=true
          else
            export COMMIT=$(git log --pretty=format:%H origin/master.. | tail -1) # first commit in branch
          fi
          hack/build-push-from-git-changes.sh
