name: Docker

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 9 * * 5'
    
jobs:
  push:
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build/Push image
        run: bash -c 'PRUNE=true PUSH=true ./update-all-images.sh'
